### ISSUE TITLE
Rules with similar triggers fire only once no matter the "fire once on page" setting

### ISSUE THREAD

**Issue by loldenburg** [janexner/launch-extension-time-spent-and-scroll-depth-event#4]
We updated the Extension to the latest version v1.5.0 and had no issue with it prior.
But now, when 2 rules (both depending on time AND scroll event) use the same scroll trigger (eg 50% scrolled), only the first one fires.
Example:
Rule A:
10s & 50% scrolled
Rule B:
15s & 50% scrolled

-> only Rule A fires.

Deactivating the Event setting to "fire once per page" does not change anything.

**Comment by janexner** [comment]
Yup, that is a result of the change I made to avoid stuff firing out of order.

The workaround is to set one rule to 51%.

The fix is for me to think about how this _should_ work. I feel that simple replacing ">" with ">=" _may_ be an option, but somehow it feels wrong.

What do you think?

**Comment by loldenburg** [comment]
"The fix is for me to think about how this should work. I feel that simple replacing ">" with ">=" may be an option, but somehow it feels wrong."

I can't follow you... :)

**Comment by janexner** [comment]
Ah, sorry. I put in code to fix "out of order" firing.

Say you have three rules, set for 25%, 50%, and 75%. When one of those rules fires, the browser will remember the scroll depth, and later ones will only fire if the depth is "deeper".

Example: Rule set to 25% fires first, 50% second, 75% third. All of those will fire as normal.

Example 2: Rule set to 50% fires first (for whatever reason), then the 25% rule would not have any effect anymore because 25 is not > 50.

In your case, 50 is not > 50, either.

So, I could change the check to >=, and that would allow your setup to work. Or add an option ("[x] allow same scroll depth to fire more than once"?).

**Comment by loldenburg** [comment]
Hi Dr. Exner,
imho every *combination* of time & scroll set in whichever rule should be its own trigger, not just every scroll depth.

Example: 
Rule A sets 15s & 50%
Rule B sets 30s & 50%
=> That would create some list of triggers, e.g. 
`[{time:15, scroll: 50}, {time: 30, scroll: 50}]`
And whenever a combination is reached, that trigger would get fired and subsequently thrown out of the list.
But maybe thinking too naively here, have not fully dug deep into the code if that makes sense in your case.

"So, I could change the check to >=, and that would allow your setup to work. "
Not sure if that would solve it. How would it work if I have:
Rule A: 50s and 10%
Rule B: 10s and 50%
If the user is at 50% scroll, rule B would trigger first. But would rule A still trigger?

**Comment by loldenburg** [comment]
@janexner what do you think? I mean for me it is fine for now if the workaround is "using 51%" in other rules, but it feels not very intuitive - in any case this should be mentioned in the documentation prominently. Just need to know if you will have any time in the near future to improve this or not. We are currently unable to do production publishes in Launch due to this.

**Comment by janexner** [comment]
I can make a quick change (using "<=" instead of "<" now, if you like.

That would mean that two separate triggers on 50% would both still fire.

In your example with 50s/10% and 10s/50%: if someone scrolls very quickly to 50%, the 10s/50% would fire, and the other one would subsequently NOT fire.

**Comment by loldenburg** [comment]
@janexner thanks!
"In your example with 50s/10% and 10s/50%: if someone scrolls very quickly to 50%, the 10s/50% would fire, and the other one would subsequently NOT fire."
=> Hmm that would still be unexpected behavior. Would it be workaround-able if the events are set as follows:
50s/11% and 10s/50%

**Comment by janexner** [comment]
I deployed version 1.6.2, which makes "prevent out-of-order" optional.

Hope that helps!

**Comment by loldenburg** [comment]
@janexner thanks, so this flag then uses the "old" logic?

**Comment by janexner** [comment]
Unchecked == old logic
Checked == new logic

Default is unchecked == old logic.

I thought that made most sense.

**Comment by loldenburg** [comment]
ah super, then we dont even need to change all the rules!

**Comment by janexner** [comment]
Yup, that was the idea.

**Comment by loldenburg** [comment]
@janexner sorry if naive question, but when will this be available in Launch?

**Comment by janexner** [comment]
Hopefully very soon. I have submitted it for public release about two hours ago. Colleagues in the US may see it today, and who knows, it may go live tonight. I'm hoping it'll be live this week, at least.

**Comment by loldenburg** [comment]
@janexner hmm now every scroll move triggers the same event again. I have gazillions of scroll events on every page now...
These are all scroll tracking events for AA for a 15 seconds and 50% event:
![image](https://user-images.githubusercontent.com/16238928/208900156-76e29f37-2724-4b52-89d7-64017a33f10e.png)
Will check this later in depth (maybe it is also something with our config, but would be weird).

**Comment by janexner** [comment]
Oh...

Check, please, and let me know.

**Comment by loldenburg** [comment]
Ok @janexner one rule had the "fire once per page" setting disabled. 
I wonder what the sense is of having such an option? Why would I want to fire the same event multiple times on the same page? Especially looking at what this causes (=dozens of events every time I scroll)...

**Comment by janexner** [comment]
If I remember correctly, I added that for rules that fire on things like 99% depth. Sometimes, you'd like to know that people scrolled all the way after other things happened.
